#undef SERV_PORT
#undef SERV_PORT_STR
#define ECHO_PORT    52661
#define ECHO_PORT_STR "52661"
#define TIME_PORT    52662
#define TIME_PORT_STR "52662"
#define ECHO_THREAD_TYPE 0
#define TIME_THREAD_TYPE 1
#define STR_ECHO_THREAD_TYPE "ECHO"
#define STR_TIME_THREAD_TYPE "TIME"
